### ISSUE TITLE
Map rendered above over widgets on Android with Flutter 3.x

### ISSUE THREAD

**Issue by aratcliffe** [m0nac0/flutter-mapbox-gl#107]
I'm using Flutter 3.0.0 and on Android the map is rendered above any other widgets. There's an issue created for this topic for flutter-map box-gl https://github.com/flutter-mapbox-gl/maps/issues/1041

**Comment by m0nac0** [comment]
Relevant issue in the Flutter repo: https://github.com/flutter/flutter/issues/103630 (feel free to upvote that one)

I'll close this issue, since there isn't anything to be done in this repo. We can only wait for flutter to fix this.
