### ISSUE TITLE
RFC: Versioning

### ISSUE THREAD

**Issue by m0nac0** [m0nac0/flutter-mapbox-gl#13]
Due to the fork, Github automatically carried over the releases from the original project. 
The question remains on how to version this plugin. Some possibilities that come to my mind, since it probably doesn't make sense to try exactly following the release schedule of the original project:
1. Delete all the existing releases and start from 0.1
2. Continue with 0.13 and from there on release on our own pace

Would be glad to hear some opinions!

**Comment by kuhnroyal** [comment]
Option 2 sounds fine.

**Comment by m0nac0** [comment]
I just released v0.13, thus going with option 2.
