### ISSUE TITLE
MaplibreMap Widget always on the top left corner

### ISSUE THREAD

**Issue by JanikoNaber** [m0nac0/flutter-mapbox-gl#136]
Hi all, and thanks for the great plugin.
In the example project, the map widget (MaplibreMap) is ignoring the flutter position and always displayed at the top left corner of the screen. 
It seems that someone else had the same issue with [mapbox_gl](https://stackoverflow.com/questions/72321054/mapbox-gl-map-tile-starts-in-top-left-corner), maybe this is related. 

Used current master with current example project. 

Flutter doctor
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.795], locale de-DE)
    • Flutter version 3.0.5 at C:\Dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (2 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Janiko\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.2.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\Janiko\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (4 available)
    • SM G981B (mobile) • RFCN20HYR0R • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22000.795]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 103.0.1264.71

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by m0nac0** [comment]
Thank you for the report.
On what platforms does this happen?
And could you try if downgrading flutter (temporarily) to 2.x solves the issue?

**Comment by kuhnroyal** [comment]
This is a duplicate of #107 and caused by the whole Flutter 3 mess around Android platform views. There are endless linked threads.
It still works with Flutter 2.10.5 and there are some related fixes in Beta 3.3.0 but I have not tried that yet.

**Comment by JanikoNaber** [comment]
@kuhnroyal you are right. A downgrade to 2.10.5 solves the issue for now. Waiting for flutter...
Thank you all for your quick feedback. 
@m0nac0 my platform is Android 12
