### ISSUE TITLE
Adding events to the map

### ISSUE THREAD

**Issue by noorbakerally** [m0nac0/flutter-mapbox-gl#146]
Like it is in the JavaScript version, is it possible to attach events to the map? For example like the `MouseTouchEvent`, more specifically `touchend`. 

```
map.on('touchend', (e) => {
console.log(e);
}
```
My exact use case is that I need to trigger a method when a long press ends.

**Comment by m0nac0** [comment]
Yes, you can specify different event callbacks in the `MaplibreMap` constructor, e.g. `onMapLongClick`

**Comment by noorbakerally** [comment]
Yes, this I got it, I'm already using onMapLongClick, but my question is can we raise an event when the long map click ends?

**Comment by noorbakerally** [comment]
I am using the native Flutter [Listener](https://api.flutter.dev/flutter/widgets/Listener-class.html) widget for this with the child being an instance of the MaplibreMap. Then, I am using the onPointerUp callback in the Listener widget to capture when the longpress ends. The issue is that onPointerUp will be called everytime the pointer is up, so even for simple clicks on the instance of the MaplibreMap. So having to keep boolean to know whether it's a longpress that is ending.

I hope it's the right way of doing.

**Comment by m0nac0** [comment]
> can we raise an event when the long map click ends?

When is the long click event raised for you? During the long click?
I unfortunately think its not possible to change this in the native SDK we're using.

**Comment by josxha** [comment]
Closing this question since there hasn't been any response in a long time.
