### ISSUE TITLE
Mapbox Styles are not compatible

### ISSUE THREAD

**Issue by user425846** [m0nac0/flutter-mapbox-gl#149]
Thank you for this package! So it is mentioned that there are only 2 breaking changes, but this is not entirely true, as mapbox styles are not compatible at all. Im aware how to use other styles, from Maptiler for example. But in my opinion, compared to the styles from Mapbox, they look like they are 5 years old visually while Mapbox is on par with Google Maps in terms of style.

Is there any possibility to add support for mapbox styles? I have already started reverse engineering the "mapbox://" links (which are breaking compatibility) using their api documention, but i dont know if i will get any results using that method and if all is even compatible in the end. I have used flutter-mapbox-gl so far which had no problem using the mapbox styles.

A reply would be greatly appreciated.

**Comment by m0nac0** [comment]
Hi, it's true that mapbox:// styles are not supported in this plugin, and I'm not sure whether one could use these styles (Mapbox may consider them to be covered by copyright etc.)

**Comment by kuhnroyal** [comment]
There are no plans to support `mapbox://` style URLs - see https://github.com/maplibre/maplibre-gl-js/discussions/1226
