### ISSUE TITLE
Getting layers and sources from the map

### ISSUE THREAD

**Issue by noorbakerally** [m0nac0/flutter-mapbox-gl#150]
From the documentation, I see that it is possible to add and remove sources using `addSource` and `removeSource`, like it is possible to add a layer using `addLayer` and `removeLayer`. However, I cannot find how to obtained the sources and layers added to the map. I would expect to find something like `getLayers` or `getSources`? Is there something such?

**Comment by m0nac0** [comment]
answered in #151
