### ISSUE TITLE
In small map features the lines are not shown correctly

### ISSUE THREAD

**Issue by TimAlber** [m0nac0/flutter-mapbox-gl#153]
When a line feature is very small that line is not dawn correctly inside the flutter maplibre map.
If the same features are displayed in the web version of maplibre everything is displayed correctly.
If the points of a line are very close to each other that line is displayed wrong.

Is there a setting somewhere to tell maplibre to show the line points regardless of how close they are to each other?
I was not able to find such a setting. In case there is no setting for this, this is a bug in my eyes.

Because this only happens on Android and iOS not on the web.

The images show the same geoJson being displayed by Flutter Maplibre and Web Maplibre.
Flutter version:
<img width="342" alt="Screenshot 2022-09-01 at 14 47 24" src="https://user-images.githubusercontent.com/8949601/187917529-67f42b81-469d-4b15-8d79-0c3857abe17d.png">

Web Version:
![Screenshot 2022-09-01 at 14 48 27](https://user-images.githubusercontent.com/8949601/187917560-be019da4-c01a-48e6-a5b8-ee0c5b66e633.png)

**Comment by m0nac0** [comment]
@TimAlber On what platform and Flutter/maplibre versions are you seeing the issue from the first picture?

**Comment by TimAlber** [comment]
I am using the latest version of you fork of maplibre.
Here the Flutter and Dart Verision:

<img width="692" alt="Screenshot 2022-09-08 at 15 59 50" src="https://user-images.githubusercontent.com/8949601/189142230-0f540917-dd9a-4858-8d5d-131e1be5dc31.png">

The Screenshot is from the Android Version, but the same happens on iOS As well.

**Comment by mariusvn** [comment]
@TimAlber do you still have the problem with the last updates ?

**Comment by TimAlber** [comment]
I dont't know if the error still exists.
I no longer work on the Projekt and i don't have access to the source code.

**Comment by mariusvn** [comment]
can you close the issue ? thanks
