### ISSUE TITLE
How to check if a source or a layer already exists

### ISSUE THREAD

**Issue by mariusvn** [m0nac0/flutter-mapbox-gl#180]
How to check if a source or a layer already exists.

I might need to do a pull request

**Comment by mariusvn** [comment]
Also, when we add a source that already exists, the error is in the library but not in the app using it

**Comment by BartoszStasiurka** [comment]
I always register source /layer even if there is an empty dataset and I don't care if it is already registered.

**Comment by mariusvn** [comment]
Would be nice if there was a way to get the liste of current layers on the map

**Comment by GaelleJoubert** [comment]
I personnally get layers with the function :
`await mapController.getLayerIds() ;`

But I would really apreciate a way to get the sources like that.
Because if I try to add a source with the same name, it crashes the app.

**Comment by mariusvn** [comment]
Oh i wasn't aware of this method, thanks for the tip.
I'll work a bit today on the lib, i'll check if i can add it

**Comment by mariusvn** [comment]
@GaelleJoubert resolved in PR https://github.com/m0nac0/flutter-maplibre-gl/pull/197
I added the getSourceIds
