### ISSUE TITLE
setLayerZoomRange

### ISSUE THREAD

**Issue by mskzo** [m0nac0/flutter-mapbox-gl#190]
Hi, 

setLayerZoomRange is not implemented but is available on native libs.
Is there any alternative to update layer zoom range?

Best Regards

**Comment by mariusvn** [comment]
I think i have a workaround to that if you are using raster layer, you can achieve that by setting the source `minZoom` and `maxZoom`.
Otherwise, I'm not sure it is possible.

**Comment by m0nac0** [comment]
This can now be achieved with the` MaplibreMapController#setLayerProperties` method added in #303 by setting the minZoom and maxZoom properties.

**Comment by LeeviLeppala** [comment]
> This can now be achieved with the` MaplibreMapController#setLayerProperties` method added in #303 by setting the minZoom and maxZoom properties.

Can you give an example? I don't understand how to set minZoom or maxZoom via LayerProperties:

_Set one or multiple properties of a layer. You can only use properties that are supported for the layer's type. So you can e.g. only use LineLayerProperties on a line layer._

But there are no minZoom or maxZoom properties in LineLayerProperties.

**Comment by m0nac0** [comment]
You are right, sorry. Currently, setLayerProperties only supports properties that are specific to one layer-type, not generic properties like minZoom. I opened #352 to track that.
