### ISSUE TITLE
[IOS] Error NSInvalidArgumentException', reason: 'Invalid filter value: filter property must be a string'

### ISSUE THREAD

**Issue by GaelleJoubert** [m0nac0/flutter-mapbox-gl#199]
Hello, 

I am adding some source and layers on my Mpas, everything works well on Android.

But on IOS I have a crash with the following error : `NSInvalidArgumentException', reason: 'Invalid filter value: filter property must be a string' 
(see bellow the whole terminal)
```

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid filter value: filter property must be a string'
*** First throw call stack:(0x1b8fdda24 0x1b23d1958 0x1b90c233c 0x1059b9c80 0x1059cbc10 0x1021533e4 0x102151c2c 0x10213ff54 0x102137018 0x1021370c4 0x109733d18 0x1091e554c 0x1bfef3850 0x1bfef47c8 0x1bfed5f18 0x1bfed5b90 0x1b9067818 0x1b904b498 0x1b904fb48 0x1ef3cb984 0x1bb3fa638 0x1bb3fa2b0 0x100fe0060 0x1d5dd9df0)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT   
  frame #0: 0x00000001f293e274 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1f293e274 <+8>:  b.lo   0x1f293e290               ; <+36>    
0x1f293e278 <+12>: stp    x29, x30, [sp, #-0x10]!    
0x1f293e27c <+16>: mov    x29, sp   
 0x1f293e280 <+20>: bl     
0x1f2939c54               ; cerror_nocancelTarget 0: (Runner) stopped
```

My code is the following : 

```
await mapController?.addSource("ski", VectorSourceProperties(url:"https://tile.map.api-k.com/data/ski.json" ));

await mapController?.addLayer("ski", "ski_pistes_blue",
      LineLayerProperties(lineOpacity: opacity,lineColor: 'rgba(192, 192, 255, 1.0)', lineCap:"round" , lineJoin:"round", lineWidth: ["interpolate", ["exponential", 2], ["zoom"], 7, 0, 14, 7]),
      sourceLayer:"pistes",
      filter: ["all",["==", "piste:difficulty", "easy"],["!has", "area"]],
      minzoom: 7
  );
  
  [...]
```

The filter seems to be the issue in IOS.
I found this issue in the mapbox-gl-native github, which seems to be the same issue, but I don't really know what to do with it ...
https://github.com/mapbox/mapbox-gl-native/issues/14805

Any idea on how to solve this issue ? thanks you very much !

**Comment by GaelleJoubert** [comment]
Ok, I have find one of the error : IOS does not support the "!has" expression.
But I have other issues now.
I have change the expression to : `["!",["has", "area"] ]`
It does not crash anymore, but I have the error message :
`NSPredicate: Use of 'mgl_does:have:' as an NSExpression function is forbidden
`
Also, I have tried to completely remove the filter. On Android the result (which is expected) is that is just draw every slope in green. But in IOS, it draws nothing ...

**Comment by GaelleJoubert** [comment]
Ok, in the end I have mannage to make it work, but I wanted to summ up all the issues I have encounter, as it might be usefull to someone and save them time !

1-  I still have the issue `"NSPredicate: Use of 'mgl_does:have:' as an NSExpression function is forbidden` displaying on the console, but it seems to actually work, and just be a print ...

2- About the line not being displayed on IOS, it was a color issue. On Android I had the following argument of LineLayerProperties: `lineColor: 'rgba(192, 192, 255, 1.0)'` , and **it works well** , but on IOS, this DOES NOT WORK !! **You have to have the color in the following format** : `#C0C0FF` It took me quite a while to reallise, because no error was displayed. So it might be smart to display an error, or at least mention something in the documentation.

3- I tried to use `textFont: "Open Sans Italic"` int the SymbolLayerProperties. Once aigain, with android, no issue, but with IOS the App crashed, with the error : `'-[__NSCFString count]: unrecognized selector sent to instance` . I did not found a workaround for this one, but I did not really care about the font, so I just removed it.

**Comment by m0nac0** [comment]
@GaelleJoubert Thank you for sharing your findings! Would you like to open a PR to document your findings regarding color? This is probably one of the unfortunate cases where the underlying libraries differ in their behaviour...

**Comment by GaelleJoubert** [comment]
sure, I can do that :) 
I can also add the info about Android being ok with expression "!has", and the workaround with IOS : ["!",["has", "value"] ]

Where this info would be relevant ? at the end of the read_me file ?

**Comment by m0nac0** [comment]
Great, the 'Fixing common issues' section in the Readme could be a good place 👍

**Comment by GaelleJoubert** [comment]
It looks like I don't have the right to creacte a new branch in the repo, should I do it from a fork ?

**Comment by m0nac0** [comment]
Thank you for the PR, closing this now since it's documented in the Readme.
