### ISSUE TITLE
Library complains about missing Mapbox Access Token 

### ISSUE THREAD

**Issue by michael-markl** [m0nac0/flutter-mapbox-gl#20]
When using this library on an Flutter Android build, it complains about a missing mapbox access token:
```
E/MapboxMapController(30570): Failed to find an Access Token in the Application meta-data. Maps may not load correctly. Please refer to the installation guide at https://github.com/tobrun/flutter-mapbox-gl#mapbox-access-token for troubleshooting advice.null
```
This message should be removed, as a token is not needed.

**Comment by m0nac0** [comment]
Good point. This warning is raised here: https://github.com/m0nac0/flutter-maplibre-gl/blob/e59a6a69ae2fe34cb2be521ae04ca0fcde7f5eb4/android/src/main/java/com/mapbox/mapboxgl/MapBoxUtils.java#L31-L33

We can definitely remove this (easily).

Related to this, I also just opened #21 (only warn about missing access tokens if a well known tile provider with mandatory access token is used).
