### ISSUE TITLE
Upgrade the android sdk to 10.0.*

### ISSUE THREAD

**Issue by mariusvn** [m0nac0/flutter-mapbox-gl#206]
The new android sdk version is out !

We should upgrade soon but I think there is a bit of change to doi because they changed some resource names.

**Comment by kuhnroyal** [comment]
Somewhat related: https://github.com/m0nac0/flutter-maplibre-gl/issues/202

**Comment by mariusvn** [comment]
yes, they change the locator implementation in 10.0.*

**Comment by stefanschaller** [comment]
Changed the android SDK to` 10.2.0` in https://github.com/maplibre/flutter-maplibre-gl/pull/270

**Comment by stefanschaller** [comment]
Changed the android SDK to 10.2.0 in https://github.com/maplibre/flutter-maplibre-gl/pull/270
