### ISSUE TITLE
Repository transfer to maplibre org account

### ISSUE THREAD

**Issue by m0nac0** [m0nac0/flutter-mapbox-gl#221]
Hey everyone,

as you might have noticed, I have transferred the repository for this project to the @maplibre organization account. I think this is a great opportunity for the project to attract more users and contributors (but I will still stay along as a maintainer for the project).

For you, not much should change, since GitHub automatically redirects references from the old repository URL to the new repository URL. GitHub reccommends that you update your local git references from the old url to the new url, as described e.g.[here](https://docs.github.com/de/repositories/creating-and-managing-repositories/transferring-a-repository#whats-transferred-with-a-repository) 

Should you notice something breaking, please open an issue!

**Comment by mariusvn** [comment]
Oh nice news !

**Comment by wipfli** [comment]
Maybe we can make an announcement on https://maplibre.org/news and social media once we have a first release... Cool that you are here now!
