### ISSUE TITLE
Abort message: 'terminating with uncaught exception of type jni::PendingJavaException'

### ISSUE THREAD

**Issue by jonasteich** [m0nac0/flutter-mapbox-gl#225]
I get this error: "Abort message: 'terminating with uncaught exception of type jni::PendingJavaException'" and my app crashes when I open a Map on an android device with `myLocationEnabled: true`. But this is just the case in my own app. When I use the example app, everything just works fine.

**Comment by Shiba-Kar** [comment]
I am also facing this error

**Comment by JulianBissekkou** [comment]
Are you able to provide a minimal reproducable example?

**Comment by jonasteich** [comment]
I found out, that this is only happening in debug mode. When running with `--release` everything works fine.

**Comment by JulianBissekkou** [comment]
@JonasTeich 
Perfect, I will close this issue now since its not a problem and might only occure during development. (hot restart/reload)
If you feel like this should be fixed then feel free to reopen the issue :)

**Comment by allou-deyforyou** [comment]
I have the same issue.
