### ISSUE TITLE
Cannot build iOS: Lexical or Preprocessor Issue

### ISSUE THREAD

**Issue by Soabbar** [m0nac0/flutter-mapbox-gl#229]
Hi
I am using Maplibre Flutter for the first time, but I cannot get it running on simulator so far.

While running `Flutter run`, I am getting:
```
Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero
exit code

Lexical or Preprocessor Issue (Xcode): 'maplibre_gl/maplibre_gl-Swift.h'
file not found

.pub-cache/git/flutter-maplibre-gl-d0ad0235cdbdc0fb3
44c1bd29283e331a3f946fa/ios/Classes/MapboxMapsPlugin.m:1:8
Could not build the application for the simulator.
```

Flutter (Channel stable, 3.7.11, on macOS 12.6.2 21G320 darwin-arm64

Is there a procedure missing or this lib doesn't support latest flutter version ?

**Comment by JulianBissekkou** [comment]
It should, we succesfully tested flutter 3.10.x
Can you provide an example app where this happens?

**Comment by m0nac0** [comment]
Closing because there was no response. Feel free to reopen if the issue persists.
