### ISSUE TITLE
Delay on iOS for Map long press

### ISSUE THREAD

**Issue by noorbakerally** [m0nac0/flutter-mapbox-gl#235]
We are noticing that the `onMapLongClick` callback takes far longer to be called on iOS than on Android, is there a way to set the duration before the callback is called?

**Comment by m0nac0** [comment]
In case this is still relevant: we don't expose any method to set that in this plugin. If it's possible to set this in the native maplibre libraries, we could expose it here. But I think it's not, so this would be a feature request for the maplibre native project.

**Comment by m0nac0** [comment]
Opened #348 for this

**Comment by m0nac0** [comment]
@noorbakerally This took some time but can now be configured on iOS.
