### ISSUE TITLE
Upgrade dependencies?

### ISSUE THREAD

**Issue by sqcsabbey** [m0nac0/flutter-mapbox-gl#239]
I'm trying to use some new Dart features, so I had to upgrade some other packages for that, but this package relies on an older version of the *image* package; any chance that could be updated? Here's the failure message I'm seeing:

> Because every version of maplibre_gl_web from git depends on image ^3.0.2 and flutter_launcher_icons >=0.12.0 depends on image ^4.0.15, maplibre_gl_web from git is incompatible with flutter_launcher_icons >=0.12.0.

**Comment by JulianBissekkou** [comment]
This was done in #248
