### ISSUE TITLE
Can not run app (Android & IOS) with Flutter version 2.10.3

### ISSUE THREAD

**Issue by tranhuyphuc9091** [m0nac0/flutter-mapbox-gl#240]
I am having issues building my app after a period of not working on the project. I have run the command 'flutter packages get' and currently I am unable to build both Android and iOS. Although I have tried various methods such as 'flutter clean' and 'pod install'.

Here is my pubspec.yaml file:
![image](https://github.com/maplibre/flutter-maplibre-gl/assets/5925243/5b3f8bea-4835-40f7-bcc7-c2134ab7fe82)

Here is my pubspec.lock file:
![image](https://github.com/maplibre/flutter-maplibre-gl/assets/5925243/9d88eff7-b50b-40a8-96ff-ac9433e43e75)

Here is my bug on Android: 
![image](https://github.com/maplibre/flutter-maplibre-gl/assets/5925243/e1ba785e-ec2a-46fd-bcdf-f1ccb7103ab4)

Here is my bug on IOS:
<img width="1033" alt="image" src="https://github.com/maplibre/flutter-maplibre-gl/assets/5925243/9d7b0bbb-6074-4de5-a38d-828af9e375d4">

Please assist me if you have any ideas. Thank you all!

**Comment by mariusvn** [comment]
Maybe it's because the URL of the repo has changed, try changing `m0nac0` to `maplibre` in the repo url

**Comment by JulianBissekkou** [comment]
Tested with 2.10.0 and it works on iOS and Android. 
If you experience any issues after changing the url as suggested feel free to reopen the issue
