### ISSUE TITLE
[Help wanted] Add callbacks for loading and error

### ISSUE THREAD

**Issue by JulianBissekkou** [m0nac0/flutter-mapbox-gl#249]
In our case we would like to display some information to the user when the map is loading or when and error happend while loading the map. This can happen when the user opens the screen that contains the map while he is offline.
Right now there is no option to do something like this and our users will see a white screen instead of a message.

I quickly checked the native sdks and I wasn't able to find an API that exposes those informations. Maybe you have an idea where this can be found.
As always: I am open to contributing this feature but I will need some guidance to get started 👍🏽

**Comment by mariusvn** [comment]
Would be nice to have but if there is no implementation of this in the native SDK, it should be added in the native SDK repo.

I dont have the time to look for a way to do  it but should be possible to intercept errors in the java code.
