### ISSUE TITLE
`widget.onStyleLoadedCallback` was called on null

### ISSUE THREAD

**Issue by JulianBissekkou** [m0nac0/flutter-mapbox-gl#253]
This error is thrown quite often, even when lunching the example app.
`onStyleLoadedCallback` is optional and therefore it shouldn't always be called when the map is ready to go.

**Comment by mariusvn** [comment]
I'll take a look when i'll check https://github.com/maplibre/flutter-maplibre-gl/issues/162. Maybe this weekend
