### ISSUE TITLE
pub.dev

### ISSUE THREAD

**Issue by birkskyum** [m0nac0/flutter-mapbox-gl#266]
There is a maplibre_gl package on pub.dev, that we did not publish, and that we have to remove

@NguyenSen - do you have any idea about it's origin?

**Comment by louwers** [comment]
@birkskyum I reaced out to `support@pub.dev`. You have a CC.

**Comment by louwers** [comment]
@m0nac0 @JulianBissekkou I set up a verified pub.dev publisher.

https://pub.dev/publishers/maplibre.org

I expect us to gain control of maplibre_gl soon.

Could you send me your e-mail addresses? I can add you to the list of admins for the maplibre.org pub.dev, if you are willing to set up a verified package. :)

**Comment by birkskyum** [comment]
@louwers  this can be closed now right?

**Comment by m0nac0** [comment]
@louwers How can I reach you? Alternatively, feel free to send me an e-mail (address is in my profile)

**Comment by birkskyum** [comment]
@m0nac0 theres a `#maplibre-flutter` channel in the [osm slack](https://slack.openstreetmap.us/)

**Comment by louwers** [comment]
@birkskyum Yes.

@m0nac0 Glad you found the new Slack channel. I am not a maintainer for this repo, but I just wanted to help you out with this. :-)
