### ISSUE TITLE
Warning about incompatible kotlin version when building an application

### ISSUE THREAD

**Issue by KostyaLocal** [m0nac0/flutter-mapbox-gl#286]
A few warning messages: 

> ... build/maplibre_gl/.transforms/e051efffd8493411969fa8add4d357bf/transformed/out/jars/classes.jar!/META-INF/maplibre_gl_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.

project android\build.gradle:
```
 ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
```

**Comment by kuhnroyal** [comment]
This is fixed.
