### ISSUE TITLE
Layer 'iG3JXRi95F_0' has an invalid value for text-font and will not render text. Output values must be contained as literals within the expression.

### ISSUE THREAD

**Issue by ThalesVonMilet** [m0nac0/flutter-mapbox-gl#288]
Hi I come from stadia map and my issue is that the literals are set wrong for my symbol layer and I don't know how to change them. 
The current ones are text-font: [case, [has, fontNames], [get, fontNames], [literal, [Open Sans Regular, Arial Unicode MS Regular]]] but I need to make them to text-font: [case, [has, fontNames], [get, fontNames], [literal, [Stadia Regular, ...]]]

Thanks for the help in regards :)

**Comment by ianthetechie** [comment]
Hello @ThalesVonMilet! Ian from the Stadia Maps team, here. Could you provide an example code snippet? It _sounds_ like you might be trying to use a theme with our styles which uses a font we don't provide (Arial Unicode MS, as we do not have a license to distribute it).

If you can provide some more details on your project (or even better, an example project, purging any API keys or other sensitive info), then I should be able to help you get past the roadblock.

**Comment by m0nac0** [comment]
Closing this since there was no response so far. Feel free to reopen if you need more help.
