### ISSUE TITLE
example app: update used location  plugin version

### ISSUE THREAD

**Issue by m0nac0** [m0nac0/flutter-mapbox-gl#324]
We currently use some fork of the location plugin in the example app.
This seems to have been added as a workaround for some issue, but the linked issue from the comments indicates we should be able to just update to version 5 of the location plugin.

Steps to do:
1. Change the reference to v5 or a more recent version of the location plugin
2. Compile example app for all 3 platforms and check that it still works, especially showing the users current location

https://github.com/maplibre/flutter-maplibre-gl/blob/81e35d7e8950ff06fcbf8a63c2324502b915d0cb/example/pubspec.yaml#L24-L30

**Comment by varunlohade** [comment]
@m0nac0  I have fixed this issue by changing the location plugin with a latest version of location package.
Tested on Android, IOS and web with users current location

**Comment by m0nac0** [comment]
Closed by #334
