### ISSUE TITLE
Investigate how to include the correct css stylesheet on the web

### ISSUE THREAD

**Issue by m0nac0** [m0nac0/flutter-mapbox-gl#331]
Currently, in https://github.com/maplibre/flutter-maplibre-gl/blob/6d24384ed93172f2680a20bf451df795aac21daa/maplibre_gl_web/lib/src/maplibre_web_gl_platform.dart#L179-L185 
we automatically load a maplibre CSS stylesheet (from https://github.com/maplibre/flutter-maplibre-gl/blob/6d24384ed93172f2680a20bf451df795aac21daa/maplibre_gl_web/lib/src/maplibre_web_gl_platform.dart#L4-L5)

But in the Readme, we also tell developers to add a maplibre css stylesheet to their index.html in https://github.com/maplibre/flutter-maplibre-gl/blob/6d24384ed93172f2680a20bf451df795aac21daa/README.md?plain=1#L59-L65

In my tests, only the stylesheet we automatically add seems to matter, removing the other one seems to have no effect.
We should investigate this, and possibly update the version and change the instructions for developers in the Readme.

**Comment by josxha** [comment]
Wasn't aware of this issue before. We removed the reference to the outdated maplibre-gl-js version that get's fetched from maptiler in https://github.com/maplibre/flutter-maplibre-gl/pull/409
