### ISSUE TITLE
[Feature] Support EdgeInsets as `padding` on `setCameraBounds`

### ISSUE THREAD

**Issue by razorness** [m0nac0/flutter-mapbox-gl#349]
Hello, thank you for this awesome package. I have a usecase where I use a large widget over a map which is displayed full screen. So, I need to set `padding` on `setCameraBounds` for earch side individually. It would be nice if this package could support `EdgeInsets` as padding option.

It is supported by [Maplibre GL JS](https://maplibre.org/maplibre-gl-js/docs/API/types/maplibregl.PaddingOptions/) and [CameraUpdateFactory.newLatLngBounds in Maplibre native](https://maplibre.org/maplibre-native/android/api/-map-libre%20-native%20for%20-android/com.mapbox.mapboxsdk.camera/-camera-update-factory/new-lat-lng-bounds.html).

**Comment by razorness** [comment]
However, found out that you can use `animateCamera` as well which supports values for each side.

**Comment by m0nac0** [comment]
If you do not want an animation, you can also use `moveCamera`. I actually don't know if we need the setCameraBounds method anymore, since there is another, more general way to update the camera. Also there are no specific methods to update other camera properties.

**Comment by razorness** [comment]
Well, I think this can be closed. Nice move to add some docs.
