### ISSUE TITLE
Android camera tracking incorrect

### ISSUE THREAD

**Issue by XanderD99** [m0nac0/flutter-mapbox-gl#375]
The onCameraTrackingChanged does not convert the android type integer back to the matching flutter enum integer.

Because of this onCameraTracking changed cannot be called as the android integers are greater then the amount of types of tracking modes in flutter. 

```dart
controller.updateMyLocationTrackingMode(MyLocationTrackingMode.TrackingCompass)
```

```dart
      case 'map#onCameraTrackingChanged':
        final int mode = call.arguments['mode'];
        print(call);
        onCameraTrackingChangedPlatform(MyLocationTrackingMode.values[mode]);
        break;
```

print statement prints out `MethodCall(map#onCameraTrackingChanged, {mode: 32})` on android while it should be `MethodCall(map#onCameraTrackingChanged, {mode: 3})`

**Comment by m0nac0** [comment]
Closed by #376
