### ISSUE TITLE
Plans to upgrade to MapLibre Native iOS 6.0.0

### ISSUE THREAD

**Issue by Camerash** [m0nac0/flutter-mapbox-gl#389]
As of January 2024, the long awaited Metal support for MapLibre has been released in version 6.0.0, [announcement here](https://maplibre.org/news/2024-01-19-metal-support-for-maplibre-native-ios-is-here)

Is there any plans or estimate on whether this will be adapted in Flutter MapLibre? It would be awesome if we can leverage the more performant graphics rendering on iOS with Flutter apps.

Also, thank you so much for this awesome project!

**Comment by m0nac0** [comment]
The breaking changes mentioned in the changelog at https://github.com/maplibre/maplibre-native/blob/main/platform/ios/CHANGELOG.md#600 sound manageable, probably mostly a bit of find-replace IDE work. 
But as already mentioned in that changelog, we would need to do some testing to make sure everything still works fine with the Metal renderer, and there still seem to be some issues with the Metal renderer like https://github.com/maplibre/maplibre-native/issues/2117
