### ISSUE TITLE
map in stack with Widget on top, if click drag on widget the map move on Web, not on iOs

### ISSUE THREAD

**Issue by chrisDupuis** [m0nac0/flutter-mapbox-gl#391]
On Web (this is ok on iOs)
I create a Stack with in first the Map then widget over the map.
When I click (and drag) on widget the widget receive the events, but the map receive the events too
and the map move as the cursor drag.

How to prevent that ?

**Comment by chrisDupuis** [comment]
To test, modify the sample CustomMarker

<code>
 @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          MaplibreMap(
            // CHD
            styleString: getSpotsydeMapStyle(),
            trackCameraPosition: true,
            onMapCreated: _onMapCreated,
            onMapLongClick: _onMapLongClickCallback,
            onCameraIdle: _onCameraIdleCallback,
            onStyleLoadedCallback: _onStyleLoadedCallback,
            initialCameraPosition: const CameraPosition(target: LatLng(35.0, 135.0), zoom: 5),
            iosLongClickDuration: const Duration(milliseconds: 200),
          ),

          Stack(
            children: _markers,
          )

 // IgnorePointer(
          //     ignoring: false,
          //     child: Stack(
          //       children: _markers,
          //     ))
</code>

The _markers should consume the mouse event

**Comment by stefanschaller** [comment]
@chrisDupuis This is a known issue with `PlatformViews` in general. Could be fixed by using the following library: https://pub.dev/packages/pointer_interceptor

Just wrap your button into a `PointerInterceptor()`

**Comment by stefanschaller** [comment]
@chrisDupuis This is a known issue with `PlatformViews` in general. Could be fixed by using the following library: https://pub.dev/packages/pointer_interceptor

Just wrap your button into a PointerInterceptor()
