### ISSUE TITLE
Update the js dependency in maplibre_gl_web

### ISSUE THREAD

**Issue by kuhnroyal** [m0nac0/flutter-mapbox-gl#398]
There is a `0.7.x` version which is used by a lot of packages already.
The currently used `0.6.7` version conflicts with this.

**Comment by josxha** [comment]
Developers are now encoraged to use the package dart:js_interop instead of [js](https://pub.dev/packages/js):

> Important: Prefer using dart:js_interop instead of this package for JS interop. See the [JS interop documentation](https://dart.dev/interop/js-interop) for more details.

**Comment by kuhnroyal** [comment]
Yes, but this is a pretty simple change to increase the dependency range and publish before introducing breaking changes.
I see you creating a lot of PRs with awesome changes, please just keep in mind that this package is used by quite a few people that need an upgrade path.

**Comment by josxha** [comment]
> Yes, but this is a pretty simple change to increase the dependency range and publish before introducing breaking changes.

You're right. It can already be done with a dependency_override but a workaround keeps being a workaround. Making a patch release that bumps depdendencies before breaking changes sounds like a good idea. 👍

> I see you creating a lot of PRs with awesome changes, please just keep in mind that this package is used by quite a few people that need an upgrade path.

Could you elaborate a bit pelase? Do you have changelog notes, deprecations or a full migration guide in mind?
