### ISSUE TITLE
Tiles are disorderly placed on the screen

### ISSUE THREAD

**Issue by YLagh01** [m0nac0/flutter-mapbox-gl#472]
### Platforms

android

### Version of flutter maplibre_gl

0.20.0

### Bug Description

Hello everyone

I'm trying to display locally hosted (with martin server) tiles on my flutter app, the software shows really good performance but the tiles are disorderly placed which makes it unusable. I'm pretty sure that the problem comes from maplibre gl library as the tiles were perfectly shown on a bunch of other softwares (QGIS, leaflet, ...). 

The style file I'm using is in the attached files.
[osm_liberty(18).json](https://github.com/user-attachments/files/16044537/osm_liberty.18.json)

Any help would be greatly appreciated!

Thank you!

Here is what is displayed on the screen at different zoom levels:
![Screenshot_20240630_135806](https://github.com/maplibre/flutter-maplibre-gl/assets/129891145/a5318afe-1aff-419d-bb57-bdf206228598)
![Screenshot_20240630_135816](https://github.com/maplibre/flutter-maplibre-gl/assets/129891145/73442aef-83af-42a3-9df0-6dcf1de5af09)
![Screenshot_20240630_135836](https://github.com/maplibre/flutter-maplibre-gl/assets/129891145/b1ef6fc1-baad-45f6-a274-8538ecb04a79)
![Screenshot_20240630_135845](https://github.com/maplibre/flutter-maplibre-gl/assets/129891145/b5e102b0-50e7-4d5f-a9ec-616a5d156302)

### Steps to Reproduce

.

### Expected Results

.

### Actual Results

.

### Code Sample

```dart
import 'package:flutter/material.dart';
import 'package:maplibre_gl/maplibre_gl.dart';

void main() {
  runApp(
    MaterialApp(home: MyApp())
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    //styleUrl is the path to a second locally hosted server which returns a JSON style file
    const styleUrl = "http://192.168.1.28:8000/api";
    return MapLibreMap(
      styleString: styleUrl,
      myLocationEnabled: true,
      initialCameraPosition: const CameraPosition(target: LatLng(0.0, 0.0)),
      trackCameraPosition: true,
    );
  }
}
```

**Comment by josxha** [comment]
This is a tile scheme problem. Could it be that sour martin tile server serves tms tiles?

https://maplibre.org/maplibre-style-spec/sources/#scheme

**Comment by josxha** [comment]
Closing this issue for now. Feel free to provide further information that tie this problem to flutter-maplibre-gl and I'll reopen.
