### ISSUE TITLE
[FEATURE] Snap to Road

### ISSUE THREAD

**Issue by Koboo** [m0nac0/flutter-mapbox-gl#493]
### Feature Description

I want a possibility to let my user's location puck snap to road. I already got an own Graphhopper instance set up, but I don't know how to let the user's location puck snap to roads. Is there already a way I can't find?

**Comment by josxha** [comment]
Hi @Koboo, there is currently no built-in feature for this. Since MapLibre Native doesn't has it either its out of scope for this package, sorry.
