### ISSUE TITLE
unable to run on ios

### ISSUE THREAD

**Issue by imSaharukh** [m0nac0/flutter-mapbox-gl#58]
``` [!] Unable to find a specification for `MapLibreAnnotationExtension (~> 0.0.1-beta.2)` depended upon by `maplibre_gl` ```

how can I add the specification?

**Comment by m0nac0** [comment]
Are you running the example project?

If not, you can try adding these lines to your Podfile: 
https://github.com/m0nac0/flutter-maplibre-gl/blob/5ede8ad75c0ab5196d86e7c1bef892811702cf0f/example/ios/Podfile#L5-L6
