### ISSUE TITLE
Adding Readme information

### ISSUE THREAD

**Issue by thertzelle** [m0nac0/flutter-mapbox-gl#59]
I believe the case is that there is not yet a published cocopod, so as a result there is a manual action to add the following lines to your podspec file:

```
pod 'MapLibre', :git =>  'https://github.com/m0nac0/maplibre-cocoapods.git'
pod 'MapLibreAnnotationExtension', :git => 'https://github.com/m0nac0/maplibre-annotation-extension.git'
```
Of course the demo includes this already, is it worth adding this to the readme of this project, until the cocopod is published (or to start publishing cocopods?)

**Comment by m0nac0** [comment]
@thertzelle Thanks for the suggestion! It took some time but I just updated the Readme.
