### ISSUE TITLE
Option to remove Mapbox logo from map

### ISSUE THREAD

**Issue by aratcliffe** [m0nac0/flutter-mapbox-gl#96]
Hi, is it possible to add an option to remove the Mapbox logo from the map? My app will use maps from a different provider.

**Comment by m0nac0** [comment]
That's not implemented, yet. You can try setting the `logoViewMargins` to something negative to move if off screen.

If you'd like to, you could supply a PR for this feature.
For the relevant APIs of the underlying MapLibre SDKs, you can check the API docs for Android: https://docs.maptiler.com/maplibre-gl-native-android/com.mapbox.mapboxsdk.maps/#logoenabled 
and for iOS this sample code: 
https://github.com/maptiler/maplibre-gl-native-ios-samples/blob/c4bc743fb703d8eaec1c94c1e49bd63d5ea51a0a/ios-swiftui/MapLibreExamples/MapLibreExamples/BasicMap.swift#L24
